services:
  react:
    container_name: live_react
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=80