services:
  nginx:
    container_name: reverse-proxy
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    # entrypoint: ["bin/sh", "-c", "/wait-for-react.sh"]
    ports:
      - "80:80"
      - "443:443"
      #expose:
      #  - "443"
    networks:
      - transcend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      # - ./nginx/wait-for-react.sh:/wait-for-react.sh  # Mount the script
    depends_on:
      - django
      - react
      #healthcheck:
      #  test: ["CMD", "sh", "-c", "test -f /etc/nginx/certs/fullchain.crt && curl -f -k https://localhost"]
      #  interval: 30s
      #  timeout: 10s
      #  retries: 3
      #  start_period: 10s
    restart: always

  react:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    expose:
      - "3000"
    networks:
      - transcend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      postgresql:
        condition: service_started
      django:
        condition: service_started
        #environment:
        #  - CHOKIDAR_USEPOLLING=TRUE
      #- PORT=80
      #restart: always

  django:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    command: ./script.sh
    expose:
      - "8000"
    env_file:
      - ./.env
    networks:
      - transcend
    volumes:
      - ./backend/:/app
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - transcend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

networks:
  transcend:
    name: transcend
    driver: bridge
