services:
  react:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - transcend
    volumes:
      - ./frontend:/app
      - react_node_modules:/app/node_modules
    depends_on:
      - postgresql
      - django
    environment:
      - CHOKIDAR_USEPOLLING=TRUE
    
  django:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: ./script.sh
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - transcend
    volumes:
      - ./backend/:/app
    depends_on:
      - postgresql
  
  postgresql:
    container_name: database
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - transcend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

        #  pgadmin:
        #    image: dpage/pgadmin4
        #    container_name: pgadmin
        #    environment:
        #      PGADMIN_DEFAULT_EMAIL: admin1@admin.com
        #      PGADMIN_DEFAULT_PASSWORD: admin
        #    ports:
        #      - "8084:80"
        #    depends_on:
        #      - "postgresql"
        #    networks:
        #      - "transcend"
        #    restart: unless-stopped


volumes:
  react_node_modules:

networks:
  transcend:
    name: transcend
    driver: bridge
