services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
        #dockerfile: Dockerfile
    command: ./script.sh
    env_file:
      - ../secrets/.env
    ports:
      - "8000:8000"
    networks:
      - transcend
    volumes:
      - ./:/app  # Mount the local folder to /app inside the container
    depends_on:
      postgresql:
        condition: service_healthy
        #restart: unless-stopped
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - transcend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U karolina1 -d karolina1"]
      interval: 10s
      timeout: 5s
      retries: 5
        #container_name: database
    ports:
      - "5432:5432"
    env_file:
      - ../secrets/.env

networks:
  transcend:
    name: transcend
    driver: bridge
